import type { EditorThemeClasses } from 'lexical'

const theme: EditorThemeClasses = {
  characterLimit: 'text-red-500',
  code: 'text-amber-500 bg-slate-700 rounded-sm px-2 py-1',
  codeHighlight: {
    atrule: 'lexical',
    attr: 'lexical',
    boolean: 'lexical',
    builtin: 'lexical',
    cdata: 'lexical',
    char: 'lexical',
    class: 'lexical',
    'class-name': 'lexical',
    comment: 'lexical',
    constant: 'lexical',
    deleted: 'lexical',
    doctype: 'lexical',
    entity: 'lexical',
    function: 'lexical',
    important: 'lexical',
    inserted: 'lexical',
    keyword: 'lexical',
    namespace: 'lexical',
    number: 'lexical',
    operator: 'lexical',
    prolog: 'lexical',
    property: 'lexical',
    punctuation: 'lexical',
    regex: 'lexical',
    selector: 'lexical',
    string: 'lexical',
    symbol: 'lexical',
    tag: 'lexical',
    url: 'lexical',
    variable: 'lexical',
  },
  heading: {
    h1: 'font-bold text-3xl',
    h2: 'font-bold text-2xl',
    h3: 'font-semibold text-xl',
    h4: 'font-semibold text-lg',
  },
  image: 'lexical',
  link: 'underline text-blue-500',
  list: {
    listitem: 'pl-4',
    nested: {
      listitem: 'pl-4',
    },
    olDepth: ['pl-4', 'pl-4', 'pl-4', 'pl-4', 'pl-4'],
    ul: 'lexical',
  },
  ltr: 'ltr',
  mark: 'lexical',
  markOverlap: 'lexical',
  paragraph: 'text-slate-700',
  quote: 'pl-4 italic text-slate-700',
  rtl: 'rtl',
  text: {
    bold: 'bold',
    code: 'text-amber-500 bg-slate-700 rounded-sm px-1.5 py-0.5',
    italic: 'italic',
    strikethrough: 'line-through',
    subscript: 'subscript',
    superscript: 'superscript',
    underline: 'underline',
    underlineStrikethrough: 'line-through',
  },
}

export default theme
